sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rodrigoillera/react-test -f ./client/Dockerfile.dev ./client

script:
  #  - docker run rodrigoillera/docker-react npm run test -- --coverage
  - docker run -e CI=true rodrigoillera/react-test npm run test

after_success:
  - docker build -t rodrigoillera/multi-client ./client
  - docker build -t rodrigoillera/multi-nginx ./nginx
  - docker build -t rodrigoillera/multi-server ./server
  - docker build -t rodrigoillera/multi-worker ./worker
  # Log into the docker CLI to connect to Docker hub
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  # Take this images and push them to Docker hub
  - docker push rodrigoillera/multi-client
  - docker push rodrigoillera/multi-nginx
  - docker push rodrigoillera/multi-server
  - docker push rodrigoillera/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-776233344088"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY